### ISSUE TITLE
Inventory cleared after release

### ISSUE THREAD

**Issue by Ac3dUd3** [graywolf336/Jail#108]
My players are getting their inventories wiped on release from the jail. and now the plugin isnt working at all.

```java
28.01 23:22:05 [Server] INFO Enabling Jail v3.0.0-SNAPSHOT-b253
28.01 23:22:05 [Server] WARN Loading the default language of: en
28.01 23:22:05 [Server] WARN If you wish to change this, please rename 'en.yml' to whatever you wish and set the config value to the name of the file.
28.01 23:22:05 [Server] ERROR Error occurred while enabling Jail v3.0.0-SNAPSHOT-b253 (Is it up to date?)
28.01 23:22:05 [Server] INFO java.lang.IllegalArgumentException: Stream cannot be null
28.01 23:22:05 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:207) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at com.graywolf336.jail.JailIO.loadLanguage(JailIO.java:69) ~[?:?]
28.01 23:22:05 [Server] INFO at com.graywolf336.jail.JailMain.onEnable(JailMain.java:75) ~[?:?]
28.01 23:22:05 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141) [PerWorldPlugins.jar:?]
28.01 23:22:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot45.jar:git-Spigot-5f38d38-12698ea]
28.01 23:22:05 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```
Config.yml http://pastebin.com/Azt2xXrM
Data.yml http://pastebin.com/xVBfXAgE

**Comment by graywolf336** [comment]
Please use https://ci.craftyn.com/job/Jail/247/ instead of the newest one. Development builds aren't working currently.

**Comment by Ac3dUd3** [comment]
it is still wiping the inventory of my players. i jail them on 'world' and the release area is spawn of 'world'

**Comment by graywolf336** [comment]
From the data.yml, it appears their inventory was empty.

**Comment by Ac3dUd3** [comment]
ive tested with alts and gave them some armor and an item and they lose it
