### ISSUE TITLE
SQLite Error in Spigot 1.10

### ISSUE THREAD

**Issue by colajunkie13** [graywolf336/Jail#128]
Using recent Spigot 1.10 i get the following SQLite error...
This error does not occur with Jail v3.0.0-SNAPSHOT-b264 or earlier.
Deleting the SQLite file (for testing) lead to the same error.

```
[20:23:48] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-3ccadba-fb568fd (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
[20:23:52] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b272
[20:23:52] [Server thread/INFO]: [Jail] Loaded the language: en
[20:23:52] [Server thread/INFO]: [Jail] Storage type selected: sqlite
[20:23:52] [Server thread/INFO]: [Jail] Connecting to the sqlite database.
[20:23:52] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b272 (Is it up to date?)
java.lang.AbstractMethodError: Method org/sqlite/Stmt.isClosed()Z is abstract
	at org.sqlite.Stmt.isClosed(Stmt.java) ~[spigot.jar:git-Spigot-3ccadba-fb568fd]
	at com.graywolf336.jail.JailIO.createTables(JailIO.java:412) ~[?:?]
	at com.graywolf336.jail.JailIO.prepareStorage(JailIO.java:127) ~[?:?]
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-3ccadba-fb568fd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot.jar:git-Spigot-3ccadba-fb568fd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
```

**Comment by colajunkie13** [comment]
Deleting the SQLite file (for testing) lead to the same error.

**Comment by colajunkie13** [comment]
This error does not occur with Jail v3.0.0-SNAPSHOT-b264 or earlier.
