### ISSUE TITLE
Bukkit/Spigot 1.11 - SQLite 3.14

### ISSUE THREAD

**Issue by colajunkie13** [graywolf336/Jail#136]
The new Bukkit/Spigot 1.11 uses SQLite 3.14 which leads to the following exception (on my testserver):

```
[12:40:53] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b274 (Is it up to date?)
java.lang.NoClassDefFoundError: org/sqlite/NativeDB
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_111]
	at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0_111]
	at java.lang.System.load(Unknown Source) ~[?:1.8.0_111]
	at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:227) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:261) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.core.NativeDB.load(NativeDB.java:56) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.sqlite.JDBC.connect(JDBC.java:88) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_111]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_111]
	at com.graywolf336.jail.JailIO.prepareStorage(JailIO.java:122) ~[?:?]
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot.jar:git-Spigot-d60de0a-a951a88]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: org.sqlite.NativeDB
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	... 31 more
```

**Comment by colajunkie13** [comment]
Looks like LWC was loading an old SQLite driver and breaking SQLite for all plugins...
Updating LWC and removing the plugins/LWC/lib folder helped.
Sorry!

**Comment by graywolf336** [comment]
Good to know, thanks for the update!
