### ISSUE TITLE
1.12 Spigot/Bukkit error on load

### ISSUE THREAD

**Issue by colajunkie13** [graywolf336/Jail#152]
With Spigot 1.12 Version git-Spigot-ede465d-bb4ae3b (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT) i get the following error, even if i remove the Jail-Folder in Plugins:

```

[02:00:35] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b278
[02:00:35] [Server thread/INFO]: [Jail] Loaded the language: en
[02:00:35] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b278 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at com.graywolf336.jail.JailIO.loadLanguage(JailIO.java:74) ~[?:?]
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:75) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

Looks like you use "loadConfiguration(InputStream)" and that was deprecated for a few years and got removed recently: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/diff/src/main/java/org/bukkit/configuration/file/YamlConfiguration.java?until=f2a9b248754b4fd91c0ae69d659a8bbf64ed4929

**Comment by colajunkie13** [comment]
I created https://github.com/graywolf336/Jail/pull/153 for that.
