### ISSUE TITLE
MC 1.12 - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by fcernese** [graywolf336/Jail#154]
Is there a 1.12 version available?  
I receive this error with the current SNAPSHOT:
[07:40:18 ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b268 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlCon
figuration;
        at com.graywolf336.jail.JailIO.loadLanguage(JailIO.java:69) ~[?:?]
        at com.graywolf336.jail.JailMain.onEnable(JailMain.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at com.jadeningle.PluginManager.Utils.Control.enablePlugin(Control.java:78) [PluginManager-Reloaded-1.0.2.jar:?]
        at com.jadeningle.PluginManager.PluginManagerCommand.loadPluginCommand(PluginManagerCommand.java:163) [PluginManager-Reloaded-1.0.2.jar:?]
        at com.jadeningle.PluginManager.PluginManagerCommand.onCommand(PluginManagerCommand.java:59) [PluginManager-Reloaded-1.0.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:630) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[07:40:18 INFO]: Jail 3.0.0-SNAPSHOT-b268 loaded!
>pm unload Jail

**Comment by graywolf336** [comment]
Fixed by #153. You can download the latest from the build server
