### ISSUE TITLE
Player doesn't get unjailed after time in 1.14.4

### ISSUE THREAD

**Issue by masterstreamer** [graywolf336/Jail#168]
This is the console error:

`[Craft Scheduler Thread - 52/WARN]: [Jail] Plugin Jail v3.0.0-SNAPSHOT-b281 generated an exception while executing task 60
java.lang.IllegalStateException: PrisonerTimeChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[spigot_server.jar:git-Spigot-56f8471-43183ea]
	at com.graywolf336.jail.JailTimer$TimeEvent.run(JailTimer.java:123) ~[Jail-3.0.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot_server.jar:git-Spigot-56f8471-43183ea]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot_server.jar:git-Spigot-56f8471-43183ea]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]`

**Comment by taylorhaight** [comment]
hey add me on discord: Taelor#9081
