### ISSUE TITLE
Jail error on server restart.

### ISSUE THREAD

**Issue by madisonofccs** [graywolf336/Jail#40]
I had restarted my server, and when entering the command /jail, I got "An Internal error occurred while attempting to perform this command". I have added the portion of the server log that shows the error.

```
[19:00:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jail' in plugin Jail v3.0.0-SNAPSHOT-b139
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.NullPointerException
	at com.graywolf336.jail.JailMain.onCommand(JailMain.java:175) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
	... 14 more
```

**Comment by graywolf336** [comment]
Was there any other error in the start up? Because what it is saying shouldn't happen unless another error has happened, but I've changed it so it sends a message instead of erroring out.

**Comment by madisonofccs** [comment]
ahh, I think I found it.

[18:50:23] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b139 (Is it up to date?)
java.lang.IllegalArgumentException: Name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.getWorld(CraftServer.java:1003) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
	at com.graywolf336.jail.JailIO.loadJailFromFlatFile(JailIO.java:604) ~[?:?]
	at com.graywolf336.jail.JailIO.loadJails(JailIO.java:578) ~[?:?]
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:77) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-Spigot-b1e6da1-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

**Comment by graywolf336** [comment]
Hmmm interesting, can you upload your jails.yml file for me somewhere?

**Comment by madisonofccs** [comment]
I think I know where its coming from, it looks like a problem with parsing data.yml which has the cell information for my jail.

**Comment by graywolf336** [comment]
Yeah that's the file I meant, can you upload it and link it to me? This way I can see where the problem is and prevent it in the future.

**Comment by madisonofccs** [comment]
http://www.mediafire.com/download/vcml9hlrxx97xhs/data.yml

**Comment by madisonofccs** [comment]
I hope that helps, I'm still trying to make sense of why its bugging out myself. Out of curiosity, does that last line do anything? It says supermaxcells: {}, which I assume is where the cell data for my jail is supposed to go (since the jail is named supermax), but the cell data is above it.

**Comment by graywolf336** [comment]
What are the worlds in your server? Just to verify that Void is a correct world.

And yeah, that's an interesting thing. Checking it out now, might have you to test a new build here shortly.

**Comment by madisonofccs** [comment]
yes, Void is the main world where the jail sits.

**Comment by madisonofccs** [comment]
I just did a test replacing cells: with the supermaxcells: and I didnt draw an error, so its promising.

**Comment by graywolf336** [comment]
What do you mean?

**Comment by madisonofccs** [comment]
on the data.yml, there are two entries for cell data, one is called cells:, the other is supermaxcells:. when its under cells: it draws an error because the format is [name]cells: {data}, the name can't be null. So I changed cells: to supermaxcells: and restarted the test server, and I didn't get any errors.

**Comment by madisonofccs** [comment]
so what i'm guessing is that when cells are created, it 'forgets' what jail its supposed to assign the cells to, and puts all the cell data under a null header. It then leaves the proper header on the file, completely empty.

**Comment by graywolf336** [comment]
To verify, you only have one jail and the name of that jail is `supermax`?

**Comment by madisonofccs** [comment]
that is correct.

**Comment by graywolf336** [comment]
Well this is rather interesting, you can delete the entire section `supermaxcells: {}` from the file you sent me and it will load correctly. I'll have to research into why it created that messed up part in the first place.

**Comment by madisonofccs** [comment]
Sounds like a long time-consuming process to me. I would look at the code on the git myself, but I'm half-asleep, and I got places to be in the morning. I hope you find out what is going on, i'll be poking around from time to time to see whats going on. If you need anything more from me, drop a message on here I'll be sure to see it :)

**Comment by graywolf336** [comment]
Sounds good, thanks for helping and bringing up the issue. The commit I just pushed should prevent the plugin from erroring out on load when a jail doesn't have a world defined, so it will at least warn the people when it can't load a jail (valid or not) and continue to load everything else.

**Comment by madisonofccs** [comment]
Not a problem, the more bugs that get caught now, the better.

**Comment by graywolf336** [comment]
Agreed! :+1:

**Comment by madisonofccs** [comment]
Well, I'll take my leave now, keep up the good work, and please don't work too hard :)

**Comment by graywolf336** [comment]
Thanks! I'll be heading that way as well shortly, have a great one! :smile:
