### ISSUE TITLE
Jail fails to load after creating a new jail with cells, then restarting the server.

### ISSUE THREAD

**Issue by madisonofccs** [graywolf336/Jail#41]
Looks like jail is returning an error when it tries to load the flatfile. I've included the error below.

```
java.lang.NullPointerException
	at com.graywolf336.jail.JailIO.loadJailFromFlatFile(JailIO.java:631) ~[?:?]
	at com.graywolf336.jail.JailIO.loadJails(JailIO.java:578) ~[?:?]
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:77) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
```

I basically deleted the data.yml file, started up the live server, then created the jail for a fresh file. I then copied the files in the folder over to my local test server, which is an identical copy of my live server, and started it up. The error showed up when I checked the logs to see if the jail loaded successfully.

**Comment by graywolf336** [comment]
Which version of the plugin are you using? More specifically, which build?

**Comment by madisonofccs** [comment]
Build #154

**Comment by madisonofccs** [comment]
it looks to me like its the same problem we were having with #40. When the server starts the load state for Jail, it attempts to read the data.yml which isn't being formatted correctly, and it throws the error.

**Comment by graywolf336** [comment]
Can you provide the data.yml?

**Comment by madisonofccs** [comment]
yeah, give me a couple of secs to send it from the live server to my mediafire

**Comment by madisonofccs** [comment]
http://www.mediafire.com/download/av7xx77zp61mm38/data.yml

**Comment by graywolf336** [comment]
Can you turn debugging on (`/togglejaildebug` or edit the config) and try with [build 155](http://ci.graywolf336.com/job/Jail/155/)? I just need the debugging output when loading it on your server.

**Comment by madisonofccs** [comment]
ok, give me a few moments

**Comment by graywolf336** [comment]
Thanks

**Comment by madisonofccs** [comment]
ok, this is pretty much all I got when I started it up with the data.yml from the live server.

[17:31:13] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b155 (Is it up to date?)
java.lang.NullPointerException
	at com.graywolf336.jail.JailIO.loadJailFromFlatFile(JailIO.java:601) ~[?:?]
	at com.graywolf336.jail.JailIO.loadJails(JailIO.java:578) ~[?:?]
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:77) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by graywolf336** [comment]
Can you provide the logs before that?

**Comment by madisonofccs** [comment]
I can give you the whole log from startup if thats what you want.

**Comment by graywolf336** [comment]
Just the lines from where Jail starts to load until that error is all I really need.

**Comment by madisonofccs** [comment]
that was all I got from the log, here is the entire log if you arent sure:

http://www.mediafire.com/download/ilxqosfd2l5pdi6/latest.log

**Comment by madisonofccs** [comment]
oh I see it now! Its really hard to see the debug data!

**Comment by graywolf336** [comment]
Okay, you can disable debugging and download the latest build...if you don't mind.

**Comment by madisonofccs** [comment]
of course I don't mind, I'm helping someone out! :)

**Comment by madisonofccs** [comment]
ok, the clip from the lastest build being run:

[17:44:05] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b157
[17:44:05] [Server thread/INFO]: [Jail] Storage type selected: flatfile
[17:44:05] [Server thread/INFO]: [Jail] Loaded the language: en
[17:44:05] [Server thread/ERROR]: [Jail] Failed to load the jail, supermax, because the world Void doesn't exist (is null).
[17:44:05] [Server thread/ERROR]: [Jail] Failed to load the jail, supermaxcells, because the world is not set.
[17:44:05] [Server thread/INFO]: [Jail] Loaded 0 jails.
[17:44:05] [Server thread/INFO]: [Jail] Loaded 0 cells.
[17:44:05] [Server thread/INFO]: [Jail] Loaded 0 prisoners.
[17:44:06] [Server thread/INFO]: [Jail] Using the Bukkit Scheduler.
[17:44:06] [Server thread/WARN]: [Jail] Can't have jail sticks without any jails.
[17:44:06] [Server thread/INFO]: [Jail] Loaded 0 jail sticks.
[17:44:06] [Server thread/INFO]: [Jail] Completed enablement.

**Comment by graywolf336** [comment]
Okay, so you don't have a world `Void` on your test server do you?

**Comment by madisonofccs** [comment]
I do have a world called Void,  its a exact duplicate of my live server.

**Comment by madisonofccs** [comment]
hmm, I wonder if its a problem with jail talking to worlds generated by Multiverse?

**Comment by madisonofccs** [comment]
let me try this on my barebones world. It doesnt have any plugins installed.

**Comment by graywolf336** [comment]
Yes it is, since those worlds aren't loaded yet even though the Jail plugin is set to load `POSTWORLD`. Let me set the plugin to load after Multiverse.

**Comment by madisonofccs** [comment]
ok, then we'll try this again, lol

**Comment by graywolf336** [comment]
Let's try after this build. I just changed up a few things. First, it will load the Jails which their world is disabled/not loaded but the Jail will be disabled. Second, it will load after multiverse.

**Comment by madisonofccs** [comment]
ok, sounds good.

**Comment by madisonofccs** [comment]
the new build is 158 correct?

**Comment by graywolf336** [comment]
Correct

**Comment by madisonofccs** [comment]
oh crud...#158 just crashed and burned...

[17:55:35] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b158
[17:55:35] [Server thread/INFO]: [Jail] Storage type selected: flatfile
[17:55:35] [Server thread/INFO]: [Jail] Loaded the language: en
[17:55:35] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b158 (Is it up to date?)
java.lang.NullPointerException
	at com.graywolf336.jail.beans.SimpleLocation.<init>(SimpleLocation.java:44) ~[?:?]
	at com.graywolf336.jail.beans.Cell.setChestLocation(Cell.java:108) ~[?:?]
	at com.graywolf336.jail.JailIO.loadJailFromFlatFile(JailIO.java:638) ~[?:?]
	at com.graywolf336.jail.JailIO.loadJails(JailIO.java:578) ~[?:?]
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:77) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-d0d1d87-15e81cf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by graywolf336** [comment]
Eh, it won't work. Hang on, forgot `Multiverse` changed their name to `Multiverse-Core`. And heh, okay that's funny.

**Comment by madisonofccs** [comment]
It happens to everyone, its just one of those long restless nights :)

**Comment by graywolf336** [comment]
Here we go, in theory it should work just fine...but let's see let you test them. :stuck_out_tongue_closed_eyes:

**Comment by graywolf336** [comment]
Did that work or have you yet to try it @madisonofccs?

**Comment by madisonofccs** [comment]
oh! sorry, was doing laundry, lol! let me get that build

**Comment by graywolf336** [comment]
Oh that's for sure more important! :stuck_out_tongue_winking_eye:

**Comment by madisonofccs** [comment]
lol, you tease! The build results:

[18:25:08] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b159
[18:25:08] [Server thread/INFO]: [Jail] Storage type selected: flatfile
[18:25:08] [Server thread/INFO]: [Jail] Loaded the language: en
[18:25:08] [Server thread/INFO]: [Jail] Loaded jail supermax with 0 prisoners and 16 cells.
[18:25:08] [Server thread/ERROR]: [Jail] Failed to load the jail, supermaxcells, because the world is not set.
[18:25:08] [Server thread/INFO]: [Jail] Loaded 1 jail.
[18:25:08] [Server thread/INFO]: [Jail] Loaded 16 cells.
[18:25:08] [Server thread/INFO]: [Jail] Loaded 0 prisoners.
[18:25:08] [Server thread/INFO]: [Jail] Using the Bukkit Scheduler.
[18:25:08] [Server thread/INFO]: [Jail] Loaded 2 jail sticks.
[18:25:08] [Server thread/INFO]: [Jail] Completed enablement.

looks like you squished that bug! Just have to figure out how to get rid of the extra "jail" thats being generated :)

**Comment by graywolf336** [comment]
Yeah...so are you able to replicate this extra thing 100% of the time?

**Comment by madisonofccs** [comment]
yeah, it happens whenever cells are created in the jail, once you do /jail stop it writes that line into data.yml. It might have something to do with how cells are being written into the flatfile.

**Comment by graywolf336** [comment]
Huh, interesting...wonder where I've messed up to cause this.

**Comment by madisonofccs** [comment]
im testing with the build 159 to see if it creates it again.

**Comment by graywolf336** [comment]
I just pushed another change, can you try build 160?

**Comment by madisonofccs** [comment]
well, the test with 159 didn't generate the additional "jail", it looks like whatever you did to kill this bug killed that one at the same time

**Comment by graywolf336** [comment]
How many cells did you create? Cause when testing I only created one cell..

**Comment by madisonofccs** [comment]
I did the test with 159 creating a new jail called Foo, and giving it 3 cells. When I was done I did /jail stop, and then stopped the server.

**Comment by graywolf336** [comment]
Well yay then! :smile: Thanks for all your help!

**Comment by madisonofccs** [comment]
its not a problem, we make a very good team!

**Comment by graywolf336** [comment]
Try to break something else now so I can fix something else haha

**Comment by madisonofccs** [comment]
if you ever need anyone to test stuff for you, you have my email already, just give me a shout :)

**Comment by graywolf336** [comment]
Will do, thanks!

**Comment by madisonofccs** [comment]
but...but, it works so good now, I don't want to break it again :(

**Comment by graywolf336** [comment]
Fair enough :)

**Comment by madisonofccs** [comment]
well, I suppose this is goodbye for now, until I break something again :). You have a good night, and take a break!

**Comment by graywolf336** [comment]
Sounds good to me, I'll be taking a break soon to grab something to eat. :hamburger: Thanks again for your help!

**Comment by madisonofccs** [comment]
no problem :) have a good one!
