### ISSUE TITLE
Not saving all cells; Not able to create cells properly; Error: PlayerInteract, Scheduler

### ISSUE THREAD

**Issue by Crafter213** [graywolf336/Jail#45]
Using Jail v3.0.0 Beta (build 139) on
CraftBukkit version git-Spigot-899f5ee-1092acb (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Error A: After creating a jail with a capital letter, it may not be able to create the cells to this jail.
(It is possible after changing the name in the config)

Error B:
When creating cells, the plugin semms to break after selecting a non-chest block.
Only some cells get saved.
When using "/jail listcells <jail>", the cells appear not in order ("cell_n7, cell_n3, cell_n9, cell_n8, cell_n17, ...")

Errors in sever.log:
While creating cells:
[21:20:55] [Craft Scheduler Thread - 862/WARN]: Exception in thread "Craft Scheduler Thread - 862" 
[21:20:55] [Craft Scheduler Thread - 862/WARN]: org.apache.commons.lang.UnhandledException: Plugin Jail v3.0.0-SNAPSHOT-b139 generated an exception while executing task 37
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.graywolf336.jail.beans.Cell.getChestLocation(Cell.java:117)
	at com.graywolf336.jail.JailIO.saveJail(JailIO.java:874)
	at com.graywolf336.jail.JailTimer$2.run(JailTimer.java:57)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[21:21:31] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Jail v3.0.0-SNAPSHOT-b139
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:463) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:724) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
	at com.graywolf336.jail.beans.Cell.getChestLocation(Cell.java:117) ~[?:?]
	at com.graywolf336.jail.JailIO.saveJail(JailIO.java:874) ~[?:?]
	at com.graywolf336.jail.JailIO.saveCell(JailIO.java:1003) ~[?:?]
	at com.graywolf336.jail.beans.Jail.addCell(Jail.java:159) ~[?:?]
	at com.graywolf336.jail.steps.CellCreationSteps.finalStep(CellCreationSteps.java:159) ~[?:?]
	at com.graywolf336.jail.steps.CellCreationSteps.thirdStep(CellCreationSteps.java:146) ~[?:?]
	at com.graywolf336.jail.steps.CellCreationSteps.step(CellCreationSteps.java:65) ~[?:?]
	at com.graywolf336.jail.listeners.PlayerListener.jailOrCellCreation(PlayerListener.java:56) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	... 16 more

[21:21:49] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Jail v3.0.0-SNAPSHOT-b139
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:463) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:724) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
	at com.graywolf336.jail.beans.Cell.getChestLocation(Cell.java:117) ~[?:?]
	at com.graywolf336.jail.JailIO.saveJail(JailIO.java:874) ~[?:?]
	at com.graywolf336.jail.JailIO.saveCell(JailIO.java:1003) ~[?:?]
	at com.graywolf336.jail.beans.Jail.addCell(Jail.java:159) ~[?:?]
	at com.graywolf336.jail.steps.CellCreationSteps.finalStep(CellCreationSteps.java:159) ~[?:?]
	at com.graywolf336.jail.steps.CellCreationSteps.thirdStep(CellCreationSteps.java:146) ~[?:?]
	at com.graywolf336.jail.steps.CellCreationSteps.step(CellCreationSteps.java:65) ~[?:?]
	at com.graywolf336.jail.listeners.PlayerListener.jailOrCellCreation(PlayerListener.java:56) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	... 16 more
[21:21:52] [Async Chat Thread - #49/INFO]: [[0;31;22mAdmin[0;37;1m] Tenzo94: [0;37;1mdas wäre doof ^^[m
[21:21:56] [Server thread/INFO]: Crafter issued server command: /jail stop
[21:21:59] [Craft Scheduler Thread - 863/WARN]: Exception in thread "Craft Scheduler Thread - 863" 
[21:21:59] [Craft Scheduler Thread - 863/WARN]: org.apache.commons.lang.UnhandledException: Plugin Jail v3.0.0-SNAPSHOT-b139 generated an exception while executing task 37
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.graywolf336.jail.beans.Cell.getChestLocation(Cell.java:117)
	at com.graywolf336.jail.JailIO.saveJail(JailIO.java:874)
	at com.graywolf336.jail.JailTimer$2.run(JailTimer.java:57)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[21:23:02] [Craft Scheduler Thread - 855/WARN]: Exception in thread "Craft Scheduler Thread - 855" 
[21:23:02] [Craft Scheduler Thread - 855/WARN]: org.apache.commons.lang.UnhandledException: Plugin Jail v3.0.0-SNAPSHOT-b139 generated an exception while executing task 37
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.graywolf336.jail.beans.Cell.getChestLocation(Cell.java:117)
	at com.graywolf336.jail.JailIO.saveJail(JailIO.java:874)
	at com.graywolf336.jail.JailTimer$2.run(JailTimer.java:57)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[21:24:05] [Craft Scheduler Thread - 864/WARN]: Exception in thread "Craft Scheduler Thread - 864" 
[21:24:05] [Craft Scheduler Thread - 864/WARN]: org.apache.commons.lang.UnhandledException: Plugin Jail v3.0.0-SNAPSHOT-b139 generated an exception while executing task 37
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.graywolf336.jail.beans.Cell.getChestLocation(Cell.java:117)
	at com.graywolf336.jail.JailIO.saveJail(JailIO.java:874)
	at com.graywolf336.jail.JailTimer$2.run(JailTimer.java:57)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

unloading the Plugin:
[21:24:34] [Server thread/INFO]: [Jail] Disabling Jail v3.0.0-SNAPSHOT-b139
[21:24:34] [Server thread/ERROR]: Error occurred while disabling Jail v3.0.0-SNAPSHOT-b139 (Is it up to date?)
java.lang.NullPointerException
	at com.graywolf336.jail.beans.Cell.getChestLocation(Cell.java:117) ~[?:?]
	at com.graywolf336.jail.JailIO.saveJail(JailIO.java:874) ~[?:?]
	at com.graywolf336.jail.JailMain.onDisable(JailMain.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at com.rylinaux.plugman.util.PluginUtil.unload(PluginUtil.java:360) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.UnloadCommand.execute(UnloadCommand.java:112) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommands.onCommand(PlugManCommands.java:100) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-899f5ee-1092acb]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]

**Comment by graywolf336** [comment]
Mind separating out the the errors into separate issues? That way we can
discuss each one individually and not get confused as to which problem we
are talking about. Thanks.
