### ISSUE TITLE
Not able to create more than one cell

### ISSUE THREAD

**Issue by stingerbee12** [graywolf336/Jail#48]
Hello,

Using the latest version snapshot from the bukkit plugin page, I type the commands as usual. I create a jail. And then I create a cell. After creating one cell, everything is fine. I am able to jail and unjail normally. However, when I choose to create another jail (typing in `/jail createcell [jail] (newcellname)`) well it works out fine. The wood sword comes and I select the points. Then the sign stage pops up and I right click the sign. 

However, after that it tells me to right click a double chest. If not needed to, right click a non-chest block. But when I right click a non-chest block, it just says in red, "No chest selected." I try right clicking everywhere on a non-chest block and it just keep saying same message. Then I put down a double chest and right click it. In green it says "Chest selected" but that's it. There's no further steps.

And if I try doing /jail stop it just exits and then never saves. I cannot progress further. 

So I'm only able to make **one** cell.

Any ideas what's the issue? Thanks!

**Comment by graywolf336** [comment]
Were any errors thrown?

**Comment by stingerbee12** [comment]
Hmm, it's been a day and I opened my server again. I'm unable to preform any jail commands as I get this message: `An internal error occurred while attempted to preform this command`

Log:
```
org.bukkit.command.CommandException: Unhandled exception executing command 'jail' in plugin Jail v3.0.0-SNAPSHOT-b139
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_20-ea]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_20-ea]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20-ea]
Caused by: java.lang.NullPointerException
	at com.graywolf336.jail.JailMain.onCommand(JailMain.java:175) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-d0d1d87-bc03b6f]
	... 14 more
>
```

**Comment by graywolf336** [comment]
Exactly what command did you try?

**Comment by stingerbee12** [comment]
/jail createcell or other /jail commands won't work.

**Comment by graywolf336** [comment]
Please update your Jail version, [located here](http://ci.graywolf336.com/job/Jail/lastSuccessfulBuild/artifact/target/Jail-3.0.0-SNAPSHOT.jar). Then report back to me.

**Comment by graywolf336** [comment]
Any news @stingerbee12?

**Comment by stingerbee12** [comment]
@graywolf336 I am so sorry for the late reply. However, after testing it out well enough, the plugin works flawlessly! Thank you so much for the link!

**Comment by stingerbee12** [comment]
Btw, when typing jail command for time, how do you make the sentence forever?

**Comment by graywolf336** [comment]
If you don't mind, can you go ahead and close this ticket and opening a new
one for the infinite time?
