### ISSUE TITLE
Problem in console

### ISSUE THREAD

**Issue by Toshka17** [graywolf336/Jail#52]
[07:23:17] [Craft Scheduler Thread - 349/ERROR]: Could not pass event PrisonerTimeChangeEvent to Jail v3.0.0-SNAPSHOT-b139
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at com.graywolf336.jail.JailTimer$TimeEvent.run(JailTimer.java:120) [Jail-3.0.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.IllegalStateException: Asynchronous entity world add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.World.b(World.java:2590) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.Chunk.addEntities(Chunk.java:793) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:40) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:113) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:88) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:558) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.Location.getBlock(Location.java:86) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	at com.graywolf336.jail.listeners.CellSignListener.changeTheCellSigns(CellSignListener.java:41) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor504.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
	... 9 more

**Comment by graywolf336** [comment]
Please update to the newest version, i believe it is still awaiting
approval on Bukkit Dev.

**Comment by graywolf336** [comment]
The update is now live: http://dev.bukkit.org/bukkit-plugins/jail/files/41-jail-v3-0-0/
