### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by mormoon** [graywolf336/Jail#61]
Since a while now, I got this error whilst loading the server.

[04:05:23] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b182
[04:05:23] [Server thread/INFO]: [Jail] Storage type selected: mysql
[04:05:23] [Server thread/INFO]: [Jail] Loaded the language: en
[04:05:23] [Server thread/INFO]: [Jail] Connecting to the MySQL database.
[04:05:23] [Server thread/INFO]: [Jail] Loaded 5 jails.
[04:05:23] [Server thread/INFO]: [Jail] Loaded 40 cells.
[04:05:23] [Server thread/INFO]: [Jail] Loaded 15 prisoners.
[04:05:23] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b182 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_31]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_31]
        at com.graywolf336.jail.listeners.CellSignListener.<init>(CellSignListener.java:31) ~[?:?]
        at com.graywolf336.jail.JailMain.onEnable(JailMain.java:98) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.3.jar:git-Spigot-1d14d5f-ba32592]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

Any change you can shed some light in whats going on? I really love your plugin btw, been using it for a while now.

**Comment by mormoon** [comment]
If you would like to know the server version I'm running atm. Here it is.

[04:05:11] [Server thread/INFO]: Starting minecraft server version 1.8.3
[04:05:11] [Server thread/INFO]: Loading properties
[04:05:11] [Server thread/INFO]: Default game type: SURVIVAL
[04:05:11] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1d14d5f-ba32592 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

**Comment by graywolf336** [comment]
Does this still happen?

**Comment by graywolf336** [comment]
I see what's causing this and will fix it. This problem happens when your sign configuration doesn't contain four lines.

**Comment by mormoon** [comment]
I see, thanks for the update!

**Comment by graywolf336** [comment]
Build 200 should now have this issue fixed.
