### ISSUE TITLE
/jail reload causes null pointer exception

### ISSUE THREAD

**Issue by hitechwizard** [graywolf336/Jail#70]
[17:57:38] [Server thread/INFO]: hitechwizard issued server command: /jail reload
[17:57:38] [Server thread/INFO]: [Jail] Loaded the language: en
[17:57:38] [Server thread/INFO]: [Jail] Connecting to the MySQL database.
[17:57:38] [Server thread/INFO]: [Jail] Loaded 2 jails.
[17:57:38] [Server thread/INFO]: [Jail] Loaded 5 cells.
[17:57:38] [Server thread/INFO]: [Jail] Loaded 0 prisoners.
[17:57:38] [Server thread/WARN]: java.lang.NullPointerException
[17:57:38] [Server thread/WARN]: 	at com.graywolf336.jail.JailMain.reloadScoreBoardManager(JailMain.java:209)
[17:57:38] [Server thread/WARN]: 	at com.graywolf336.jail.JailMain.reloadEverything(JailMain.java:200)
[17:57:38] [Server thread/WARN]: 	at com.graywolf336.jail.command.subcommands.JailReloadCommand.execute(JailReloadCommand.java:22)
[17:57:38] [Server thread/WARN]: 	at com.graywolf336.jail.command.JailHandler.parseCommand(JailHandler.java:135)
[17:57:38] [Server thread/WARN]: 	at com.graywolf336.jail.JailMain.onCommand(JailMain.java:187)
[17:57:38] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:57:38] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:57:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[17:57:38] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:57:38] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[17:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[17:57:38] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by graywolf336** [comment]
When you did that reload had you changed anything related to the
scoreboard?

**Comment by hitechwizard** [comment]
no, but we don't use any scoreboard plugins outside of the latest Spigot/Bukkit build. Looking through yesterday's log, I also noticed this:

[11:23:47] [Server thread/INFO]: [Jail] Loading Jail v3.0.0-SNAPSHOT-b187
[11:24:04] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b187
[11:24:04] [Server thread/INFO]: [Jail] Storage type selected: mysql
[11:24:04] [Server thread/INFO]: [Jail] Loaded the language: en
[11:24:04] [Server thread/INFO]: [Jail] Connecting to the MySQL database.
[11:24:04] [Server thread/INFO]: [Jail] Loaded 2 jails.
[11:24:04] [Server thread/INFO]: [Jail] Loaded 5 cells.
[11:24:04] [Server thread/INFO]: [Jail] Loaded 0 prisoners.
[11:24:04] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b187 (Is it up to date?)
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:98) ~[?:?]
[11:24:04] [Server thread/INFO]: Enable check:Jail

**Comment by graywolf336** [comment]
I'm talking about in the config of Jail. Post your configuration please.

**Comment by hitechwizard** [comment]
May have figured it out.... apparently the single quotes are missing around:  Charged with: 


# ###################
# Jail v3.0.0-SNAPSHOT-b187 config file
# Note: You -must- use spaces instead of tabs!
# ###################
system:
  version: 3
  debug: false
  language: en
  updates:
    channel: bukkit
    notification: true
    time: 1h
  useBukkitTimer: true
storage:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    username: xxxxxxxxxxxxxxxxxxxx
    password: xxxxxxxxxxxxxxxxxxxxx
    database: xxxxxxxxxxxxxxxxxxxxx
    prefix: j3_
jailing:
  during:
    blockBreakPenalty: 5m
    blockBreakProtection: true
    blockBreakWhiteList:
    - crops
    - carrot
    - potato
    blockPlacePenalty: 5m
    blockPlaceProtection: true
    blockPlaceWhiteList:
    - crops
    - carrot
    - potato
    cellsign:
    - '%player%'
    - '%timeinminutes% mins'
    - Charged with: null
    - '%reason%'
    commandPenalty: 5m
    commandProtection: true
    commandWhitelist:
    - /ping
    - /list
    - /jail status
    - /jail pay
    - /helpop
    countDownTimeWhileOffline: false
    cropTramplingPenalty: 5m
    cropTramplingProtection: true
    foodControl:
      enabled: true
      max: 20
      min: 10
    ignoreSleeping: true
    maxAFKTime: 10m
    movePenalty: 10m
    moveProtection: true
    openChest: true
    preventInteractionBlocks:
    - wooden_door
    - iron_door_block
    preventInteractionBlocksPenalty: 5m
    preventInteractionItems: []
    preventInteractionItemsPenalty: 5m
    recieveMessages: true
    scoreboard:
      enabled: false
      title: Jail Info
      time: '&aTime:'
  jail:
    automaticCell: true
    automaticMute: true
    broadcastJailing: true
    clothing:
      enabled: true
      helmet: leather_helmet~175,105,33
      chest: leather_chestplate~175,105,33
      legs: leather_leggings~175,105,33
      boots: leather_boots~175,105,33
    commands: []
    default:
      jail: nearest
      time: 30m
    gameMode: adventure
    inventory:
      blacklist: []
      store: true
    log:
      console: true
      profile: true
  release:
    backToPreviousPosition: false
    commands: []
    restorePreviousGameMode: false
    teleport: true
jails:
  endermenProtection: true
  explosionProtection: true
jailpay:
  enabled: true
  item: air
  pricePerMinute: 1.5
  priceInfinite: 10000
jailstick:
  enabled: false
  sticks:
  - stick,30m,,Running away,-1
  - blaze_rod,15m,,Having too much fun,6
jailvote:
  enabled: true 
  voteTimer: 60s
  minimumYes: 5
  reason: Jailed by players via Jail Vote
  time: 5m

**Comment by graywolf336** [comment]
Can you edit the comment and add the code markdown to the config you posted
so it looks prettier? :)

**Comment by hitechwizard** [comment]
oops. :)

**Comment by graywolf336** [comment]
Yeah the line with `- Charged with: null` needs quotes around it I believe.

**Comment by hitechwizard** [comment]
That was the issue. Thanks for quick response!

[18:37:20] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b187
[18:37:20] [Server thread/INFO]: [Jail] Storage type selected: mysql
[18:37:20] [Server thread/INFO]: [Jail] Loaded the language: en
[18:37:20] [Server thread/INFO]: [Jail] Connecting to the MySQL database.
[18:37:20] [Server thread/INFO]: [Jail] Loaded 2 jails.
[18:37:20] [Server thread/INFO]: [Jail] Loaded 5 cells.
[18:37:20] [Server thread/INFO]: [Jail] Loaded 0 prisoners.
[18:37:20] [Server thread/INFO]: [Jail] Using the Bukkit Scheduler.
[18:37:20] [Server thread/INFO]: [Jail] Completed enablement.

...

[18:38:07] [Server thread/INFO]: hitechwizard issued server command: /jail reload
[18:38:07] [Server thread/INFO]: [Jail] Loaded the language: en
[18:38:07] [Server thread/INFO]: [Jail] Loaded 2 jails.
[18:38:07] [Server thread/INFO]: [Jail] Loaded 5 cells.
[18:38:07] [Server thread/INFO]: [Jail] Loaded 0 prisoners.

**Comment by graywolf336** [comment]
No problem! Glad we could get it figured out. :)
