### ISSUE TITLE
Support for Spigot 1.8.7

### ISSUE THREAD

**Issue by tonkku107** [graywolf336/Jail#87]
Can you update Jail for Spigot 1.8.7?
The plugin is not loading correctly.

**Comment by graywolf336** [comment]
Please provide the errors which are happening.

**Comment by tonkku107** [comment]
```
[12:04:34] [Server thread/INFO]: [Jail] Loading Jail v3.0.0-SNAPSHOT-b182
[12:04:50] [Server thread/INFO]: [Jail] Enabling Jail v3.0.0-SNAPSHOT-b182
[12:04:50] [Server thread/INFO]: [Jail] Storage type selected: sqlite
[12:04:50] [Server thread/INFO]: [Jail] Loaded the language: en
[12:04:50] [Server thread/INFO]: [Jail] Connecting to the sqlite database.
[12:04:50] [Server thread/ERROR]: Error occurred while enabling Jail v3.0.0-SNAPSHOT-b182 (Is it up to date?)
java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
	at com.graywolf336.jail.JailIO.getConnection(JailIO.java:170) ~[?:?]
	at com.graywolf336.jail.JailIO.createTables(JailIO.java:208) ~[?:?]
	at com.graywolf336.jail.JailIO.prepareStorage(JailIO.java:111) ~[?:?]
	at com.graywolf336.jail.JailMain.onEnable(JailMain.java:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [minecraft_server.jar:git-Spigot-b2c2c63-a3cb1bc]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```
That's all

**Comment by graywolf336** [comment]
Please update to the latest development version.
