### ISSUE TITLE
Players can escape

### ISSUE THREAD

**Issue by tonkku107** [graywolf336/Jail#88]
I got the dev build now and configured a jail. I tested a jail, and the player was able to go and adventure around the world. In the config moveProtection is true.

**Comment by graywolf336** [comment]
Interesting, I just started up a new test server with Jail and created a jail with a cell in it. Jailed my player and then tried to walk out but kept getting teleported back in my cell. Turn on debugging, `/togglejaildebug` and try again, then report back with logs after trying.

**Comment by tonkku107** [comment]
```
[18:56:04] [Server thread/INFO]: tonkku107 issued server command: /jail minecraftgal798 -t 2 -j supercell -c cell1 -r test
[18:56:04] [Server thread/INFO]: [CommandLogger] Player: tonkku107 Command: /jail minecraftgal798 -t 2 -j supercell -c cell1 -r test
[18:56:04] [Server thread/INFO]: [Jail] [Debug]: We are getting ready to handle jailing: minecraftgal798
[18:56:04] [Server thread/INFO]: [Jail] [Debug]: Teleporting minecraftgal798 to supercell in the cell cell1's in: Location{world=CraftWorld{name=world},x=203.49188195584716,y=67.0,z=154.32895448755556,pitch=3.7501028,yaw=-180.45813}
[18:56:04] [Server thread/INFO]: [Jail] [Debug]: Took 59 millis to save the jail supercell.
[18:56:04] [Server thread/INFO]: [Jail] [Debug]: Adding 4b46f5da-deea-4c88-9aef-bae39025dba6 to the cache.
[18:56:05] [Server thread/INFO]: minecraftgal798 issued server command: /tp skywarp626 minecraftgal798
[18:56:05] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:05] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:05] [Server thread/INFO]: [CommandLogger] Player: minecraftgal798 Command: /tp skywarp626 minecraftgal798
[18:56:05] [Craft Scheduler Thread - 162/INFO]: [Jail] [Debug]: Took 70 millis to save the jail supercell.
[18:56:23] [Server thread/INFO]: minecraftgal798 issued server command: /home
[18:56:23] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:23] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:23] [Server thread/INFO]: [CommandLogger] Player: minecraftgal798 Command: /home
[18:56:32] [Async Chat Thread - #15/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:32] [Async Chat Thread - #15/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:41] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:41] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:41] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:45] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:45] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:45] [Server thread/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:53] [Async Chat Thread - #15/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:56:53] [Async Chat Thread - #15/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:57:05] [Craft Scheduler Thread - 184/INFO]: [Jail] [Debug]: Took 55 millis to save the jail supercell.
[18:57:27] [Async Chat Thread - #15/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:57:27] [Async Chat Thread - #15/INFO]: [Jail] [Debug]: 4b46f5da-deea-4c88-9aef-bae39025dba6 is in the cache (getJailPlayerIsIn).
[18:57:50] [Server thread/INFO]: [Jail] [Debug]: Tab Complete Args (1) for 'unjail': mine
[18:57:50] [Server thread/INFO]: tonkku107 issued server command: /unjail minecraftgal798
[18:57:50] [Server thread/INFO]: [CommandLogger] Player: tonkku107 Command: /unjail minecraftgal798
[18:57:50] [Server thread/INFO]: [Jail] [Debug]: Removing 4b46f5da-deea-4c88-9aef-bae39025dba6 from the cache.
[18:57:50] [Server thread/INFO]: [Jail] [Debug]: Removing minecraftgal798 (4b46f5da-deea-4c88-9aef-bae39025dba6) from MySQL database.
```

**Comment by tonkku107** [comment]
The player went outside the jail area and came back, left again and was unjailed outside the area

**Comment by graywolf336** [comment]
Sounds like your jail area isn't defined correctly...

**Comment by tonkku107** [comment]
I used the wooden sword in the process of /jail create

**Comment by tonkku107** [comment]
Should I recreate the jail with the debugging?

**Comment by graywolf336** [comment]
Yes please.

**Comment by tonkku107** [comment]
```
[19:53:21] [Server thread/INFO]: tonkku107 issued server command: /jail create supercell
[19:53:21] [Server thread/INFO]: [CommandLogger] Player: tonkku107 Command: /jail create supercell
[19:53:23] [Server thread/INFO]: [Jail] [Debug]: Stepping into creating a jail.
[19:53:23] [Server thread/INFO]: [Jail] [Debug]: Stepping into step #1
[19:53:35] [pool-6-thread-1/INFO]: GroupManager - INFO -  Data files refreshed.
[19:53:45] [Server thread/INFO]: [Jail] [Debug]: Stepping into creating a jail.
[19:53:45] [Server thread/INFO]: [Jail] [Debug]: Stepping into step #2
[19:53:56] [Server thread/INFO]: [Jail] [Debug]: Stepping into creating a jail.
[19:53:56] [Server thread/INFO]: [Jail] [Debug]: Stepping into step #3
[19:54:03] [Server thread/INFO]: [Jail] [Debug]: Stepping into creating a jail.
[19:54:03] [Server thread/INFO]: [Jail] [Debug]: Stepping into step #4
[19:54:03] [Server thread/INFO]: [Jail] [Debug]: Took 28 millis to save the jail supercell.
[19:54:15] [Server thread/INFO]: tonkku107 issued server command: /jail createcell
[19:54:15] [Server thread/INFO]: [CommandLogger] Player: tonkku107 Command: /jail createcell
[19:54:15] [Server thread/INFO]: [Jail] [Debug]: Sender didn't provide enough arguments.
[19:54:20] [Server thread/INFO]: tonkku107 issued server command: /jail createcell supercell cell1
[19:54:20] [Server thread/INFO]: [CommandLogger] Player: tonkku107 Command: /jail createcell supercell cell1
[19:54:21] [Craft Scheduler Thread - 274/INFO]: [Jail] [Debug]: Took 27 millis to save the jail supercell.
[19:54:29] [Server thread/INFO]: [Jail] [Debug]: Stepping into creating a cell.
[19:54:29] [Server thread/INFO]: [Jail] [Debug]: Stepping into step #1
[19:54:33] [Server thread/INFO]: [Jail] [Debug]: Stepping into creating a cell.
[19:54:33] [Server thread/INFO]: [Jail] [Debug]: Stepping into step #2
[19:54:36] [Server thread/INFO]: [Jail] [Debug]: Stepping into creating a cell.
[19:54:36] [Server thread/INFO]: [Jail] [Debug]: Stepping into step #2
[19:54:44] [Server thread/INFO]: [Jail] [Debug]: Stepping into creating a cell.
[19:54:44] [Server thread/INFO]: [Jail] [Debug]: Stepping into step #3
[19:54:44] [Server thread/INFO]: [Jail] [Debug]: Saving the cell cell1
[19:54:50] [Server thread/INFO]: tonkku107 issued server command: /jail stop
[19:54:50] [Server thread/INFO]: [CommandLogger] Player: tonkku107 Command: /jail stop
```

**Comment by tonkku107** [comment]
Oh, just noticed this when I deleted the jail
```
[19:52:53] [Server thread/INFO]: tonkku107 issued server command: /jail delete supercell
[19:52:53] [Server thread/INFO]: [CommandLogger] Player: tonkku107 Command: /jail delete supercell
[19:52:57] [Server thread/INFO]: tonkku107 issued server command: /jail confirm
[19:52:57] [Server thread/INFO]: [CommandLogger] Player: tonkku107 Command: /jail confirm
[19:52:57] [Server thread/WARN]: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (near "limit": syntax error)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:404)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:399)
[19:52:57] [Server thread/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:383)
[19:52:57] [Server thread/WARN]: 	at com.graywolf336.jail.JailIO.removeCell(JailIO.java:1133)
[19:52:57] [Server thread/WARN]: 	at com.graywolf336.jail.JailIO.removeJail(JailIO.java:1173)
[19:52:57] [Server thread/WARN]: 	at com.graywolf336.jail.JailManager.removeJail(JailManager.java:127)
[19:52:57] [Server thread/WARN]: 	at com.graywolf336.jail.JailManager.deleteJail(JailManager.java:526)
[19:52:57] [Server thread/WARN]: 	at com.graywolf336.jail.command.subcommands.JailConfirmCommand.execute(JailConfirmCommand.java:75)
[19:52:57] [Server thread/WARN]: 	at com.graywolf336.jail.command.JailHandler.parseCommand(JailHandler.java:219)
[19:52:57] [Server thread/WARN]: 	at com.graywolf336.jail.JailMain.onCommand(JailMain.java:192)
[19:52:57] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:52:57] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:52:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1149)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:984)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[19:52:57] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:52:57] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[19:52:57] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[19:52:57] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:52:57] [Server thread/ERROR]: [Jail] ---------- Jail Error!!! ----------
[19:52:57] [Server thread/ERROR]: [Jail] Error while removing the cell 'cell1' from the Jail 'supercell', please check the error and fix what is wrong.
```

**Comment by graywolf336** [comment]
Open a new issue for that deleting error.

Have you tried to jail someone again with the new jail?

**Comment by tonkku107** [comment]
Yes, the same thing happens still

**Comment by graywolf336** [comment]
What all plugins do you have? Did you change that setting after having it disabled when the server started up? Because that's one feature which won't be enabled on a jail reload due to the listener not being registered when it is disabled on the plugin startup.

**Comment by tonkku107** [comment]
It was in the config as true when I started.
I changed it to false and reloaded, then changed it to true and restarted and it's working now.

**Comment by tonkku107** [comment]
P.S I hope you redo the guards soon ;)

**Comment by graywolf336** [comment]
Ah okay, glad to hear it's working.

My plan for them is to release another beta soon which has a lot of bug fixes after I finish the help for each item. Then after the next beta is released I'll start work on the guards, so it won't be right away but won't be super far out.

**Comment by graywolf336** [comment]
I got inspired to see if it was possible to do it dynamically and it is. :smile: hopefully this issue won't come up in the future from anyone else.

**Comment by tonkku107** [comment]
Great. :smile: Have fun continuing the plugin
