### ISSUE TITLE
cannot create jail - selection is failing

### ISSUE THREAD

**Issue by AvatarAcid** [graywolf336/Jail#95]
Hello,

This is the first time I've used Jail(default unmodified config) so forgive me if this is an obvious thing, but I've done /jail create jail1 and the plugin has asked me to select a cuboid via right click and wooden sword.

When I do this, and assure you I am actually right clicking not left, I get no confirmation and doesn't seem to work.

I have tried outside of my worldguard region in survival gamemode also, still failed.

Jail Version: 3.0.0-SNAPSHOT-b182
Spigot 1.8-R0.1

Any help is appreciated.

**Comment by graywolf336** [comment]
Is another plugin preventing you from selecting? Sometimes vanish does and
other plugins could too.

**Comment by AvatarAcid** [comment]
I just killed all plugins except Jail, same issue so far!

**Comment by AvatarAcid** [comment]
As well as not being able to use Jail plugin, I get this from time to time in server console:
[04:50:51 WARN]: java.io.IOException: Server returned HTTP response code: 504 fo
r URL: https://api.curseforge.com/servermods/files?projectIds=31139
[04:50:51 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputS
tream(Unknown Source)
[04:50:51 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.get
InputStream(Unknown Source)
[04:50:51 WARN]:        at com.graywolf336.jail.Update.query(Update.java:61)
[04:50:51 WARN]:        at com.graywolf336.jail.JailMain$1.run(JailMain.java:273
)
[04:50:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.ru
n(CraftTask.java:71)
[04:50:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTa
sk.run(CraftAsyncTask.java:53)
[04:50:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[04:50:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[04:50:51 WARN]:        at java.lang.Thread.run(Unknown Source)
[04:50:51 ERROR]: [Jail] There was an error checking for an update, please see t
he above stacktrace for details before reporting.

**Comment by AvatarAcid** [comment]
Upgraded to CraftBukkit-Spigot v1.8.8-R0.1 - no change.

**Comment by graywolf336** [comment]
That error is due to Curse's servers being down: `Server returned HTTP response code: 504 fo
r URL: https://api.curseforge.com/servermods/files?projectIds=31139`

**Comment by AvatarAcid** [comment]
Ok, any advice on getting right click with wooden sword going to create the jail?

**Comment by graywolf336** [comment]
Toggle debugging on, `/togglejaildebug` and then try to restart everything again. Upload the log around that and we'll go from there. If this returns nothing, then we'll do some changes.

**Comment by AvatarAcid** [comment]
It isn't outputting anything to console when I right click. I did a test to confirm debug was on and it is, but no help:
[18:01:01 INFO]: AvatarAcid issued server command: /jail create
[18:01:01 INFO]: [Jail] [Debug]: Sender didn't provide enough arguments.
[18:01:05 INFO]: AvatarAcid issued server command: /jail create wtf

**Comment by zedwick** [comment]
I am also experiencing this issue, no log output using /togglejaildebug.

Right clicking with wooden sword in hand provides no feedback, entering the /jail create command again tells me I am already creating a jail and still need to select the first point.

**Comment by miketorman** [comment]
same issue

**Comment by graywolf336** [comment]
I think something is messing with the right click of the swords, so I'll change the item to something that almost always sends the clicks
